name       : python-httplib2
version    : 0.19.0
release    : 5
source     :
    - https://pypi.io/packages/source/h/httplib2/httplib2-0.19.0.tar.gz : e0d428dad43c72dbce7d163b7753ffc7a39c097e6788ef10f4198db69b92f08e
license    : MIT
component  : programming.python
summary    : Small, fast HTTP client library for Python
description: |
    Small, fast HTTP client library for Python. Features persistent connections, cache, Appengine support.
builddeps  :
    - pkgconfig(python3)
    - python-six
rundeps    :
    - pyparsing
setup      : |
    # Don't hardcode support for one old version please...
    sed -i 's/==/>=/' requirements-test.txt
build      : |
    %python3_setup
install    : |
    %python3_install
# Requires python-pytest-xdist, use wheel and networking for local check.
#check      : |
#    %python3_test
#    %python_test
