name       : python-httplib2
version    : 0.21.0
release    : 9
source     :
    - https://github.com/httplib2/httplib2/archive/refs/tags/v0.21.0.tar.gz : b60f25d988e8c271d05db06f76d2174e32151fc87f4c1bc49774e99fe580d4b1
homepage   : https://github.com/httplib2/httplib2
license    : MIT
component  : programming.python
summary    : Small, fast HTTP client library for Python
description: |
    Small, fast HTTP client library for Python. Features persistent connections, cache, Appengine support.
builddeps  :
    - python-six
rundeps    :
    - pyparsing
setup      : |
    # Don't hardcode support for one old version please...
    sed -i 's/==/>=/' requirements-test.txt
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # Requires python-pytest-xdist, use wheel and networking for local check.
#    %python3_test
