name       : python-httplib2
version    : 0.14.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/ce/2e/87461bfbb7e561203b759b3f7f639e2144226604372830d00a8279960ae1/httplib2-0.14.0.tar.gz : 34537dcdd5e0f2386d29e0e2c6d4a1703a3b982d34c198a5102e6e5d6194b107
license    : MIT
component  : programming.python
summary    : Small, fast HTTP client library for Python
description: |
    Small, fast HTTP client library for Python. Features persistent connections, cache, Appengine support.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-six
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    %python_install
#check      : |
#    %python3_test
#    %python_test
