name       : python-httplib2
version    : 0.10.3
release    : 1
source     :
    - https://pypi.python.org/packages/e4/2e/a7e27d2c36076efeb8c0e519758968b20389adf57a9ce3af139891af2696/httplib2-0.10.3.tar.gz : e404d3b7bd86c1bc931906098e7c1305d6a3a6dcef141b8bb1059903abb3ceeb
license    : MIT
component  : programming.python
summary    : Small, fast HTTP client library for Python
description: |
    Small, fast HTTP client library for Python. Features persistent connections, cache, Appengine support.
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    %python_install
